serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://localhost:4444
  consent: http://localhost:5002/api/consent
  login: http://localhost:5002/login
  logout: http://localhost:5002/logout

secrets:
  system:
    - e5Mcyq@EU@iT=1hH

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: e5Mcyq@EU@iT=1hH
log:
  level: debug
