import { Role } from '../types'

export const ROUTES = {
  HOME: '/',
  DASHBOARD: {
    HOME: '/dashboard',
    ASSETS: '/dashboard/assets',
    ADD_ASSETS: '/dashboard/assets/add-assets',
    PROFILE: '/dashboard/profile',
    USERS: '/dashboard/users',
    COMPANIES: '/dashboard/companies',
    ACCOUNTING: '/dashboard/accounting',
  },
}

export const FEDERATOR_PROTECTED_ROUTES = [
  ROUTES.DASHBOARD.HOME,
  ROUTES.DASHBOARD.COMPANIES,
  ROUTES.DASHBOARD.PROFILE,
  ROUTES.DASHBOARD.USERS,
  ROUTES.DASHBOARD.ASSETS,
  ROUTES.DASHBOARD.ADD_ASSETS,
  ROUTES.DASHBOARD.ACCOUNTING,
]

export const PRINCIPAL_PROTECTED_ROUTES = [
  ROUTES.DASHBOARD.HOME,
  ROUTES.DASHBOARD.PROFILE,
  ROUTES.DASHBOARD.USERS,
  ROUTES.DASHBOARD.ASSETS,
  ROUTES.DASHBOARD.ADD_ASSETS,
  ROUTES.DASHBOARD.ACCOUNTING,
]

export const PROVIDER_PROTECTED_ROUTES = [
  ROUTES.DASHBOARD.HOME,
  ROUTES.DASHBOARD.ASSETS,
  ROUTES.DASHBOARD.ADD_ASSETS,
  ROUTES.DASHBOARD.ACCOUNTING,
]

export const USER_PROTECTED_ROUTES = [ROUTES.DASHBOARD.HOME, ROUTES.DASHBOARD.ASSETS, ROUTES.DASHBOARD.ACCOUNTING]

export const ROLE_PROTECTED_ROUTES_MAP = {
  [Role.federator]: FEDERATOR_PROTECTED_ROUTES,
  [Role.principal]: PRINCIPAL_PROTECTED_ROUTES,
  [Role.provider]: PROVIDER_PROTECTED_ROUTES,
  [Role.user]: USER_PROTECTED_ROUTES,
}
