export const ERRORS = {
  CANNOT_CONNECT_TO_DATABASE: 'Cannot connect to database',
  UNAUTHORIZED: 'Unauthorized',
  BAD_REQUEST: 'Bad Request',
  FORBIDDEN: 'Forbidden',
  INTERNAL_SERVER_ERROR: 'Internal Server Error',
  NOT_FOUND: 'Not found',
  ASSET_EXISTS: 'Asset already exists',
  ASSETS_NOT_FOUND: 'Assets not found',
  ASSET_INVALID: 'Asset validation failed',
  ASSET_FILE_NOT_FOUND: 'No valid metadata.json found',
  CID_MISSING: 'CID is required',
  DOMAIN_METADATA_INVALID: 'domainMetadata.json validation failed',
  MANIFEST_INVALID: 'manifest.json validation failed',
  FILES_NOT_FOUND: 'File(s) not found',
  FILE_NOT_FOUND: 'File not found',
  SIGNED_URL_MISSING: 'No signed URL',
  FILE_TYPE_MISSING: 'File type is missing',
  FAILED_UPLOAD: 'Failed to upload to S3',
  README_FILE_NOT_FOUND: 'README.md file not found',
  NOT_ALLOWED_TO_DELETE_ASSET: 'Not allowed to delete asset',
  MINTED_ASSET_CANNOT_BE_DELETED: 'Minted asset cannot be deleted',
  ASSET_UPLOAD_FAILED: 'Asset upload failed',
  NETWORK_ERROR: 'Network error',
}

export const ERROR_CODES = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
}
