import { Role } from '../types'

export const ROUTES = {
  HOME: '/',
  DASHBOARD: {
    HOME: '/dashboard',
    ASSETS: '/dashboard/assets',
    ADD_ASSETS: '/dashboard/assets/add-assets',
    PROFILE: '/dashboard/profile',
    USERS: '/dashboard/users',
    MEMBERS: '/dashboard/members',
    ACCOUNTING: '/dashboard/accounting',
  },
}

export const FEDERATOR_AUTHORIZED_ROUTES = [
  ROUTES.DASHBOARD.HOME,
  ROUTES.DASHBOARD.MEMBERS,
  ROUTES.DASHBOARD.PROFILE,
  ROUTES.DASHBOARD.USERS,
  ROUTES.DASHBOARD.ASSETS,
  ROUTES.DASHBOARD.ADD_ASSETS,
  ROUTES.DASHBOARD.ACCOUNTING,
]

export const PRINCIPAL_AUTHORIZED_ROUTES = [
  ROUTES.DASHBOARD.HOME,
  ROUTES.DASHBOARD.PROFILE,
  ROUTES.DASHBOARD.USERS,
  ROUTES.DASHBOARD.ASSETS,
  ROUTES.DASHBOARD.ADD_ASSETS,
  ROUTES.DASHBOARD.ACCOUNTING,
]

export const PROVIDER_AUTHORIZED_ROUTES = [
  ROUTES.DASHBOARD.HOME,
  ROUTES.DASHBOARD.ASSETS,
  ROUTES.DASHBOARD.ADD_ASSETS,
  ROUTES.DASHBOARD.ACCOUNTING,
]

export const USER_AUTHORIZED_ROUTES = [ROUTES.DASHBOARD.HOME, ROUTES.DASHBOARD.ASSETS, ROUTES.DASHBOARD.ACCOUNTING]

export const ROLE_PROTECTED_ROUTES_MAP = {
  [Role.federator]: FEDERATOR_AUTHORIZED_ROUTES,
  [Role.principal]: PRINCIPAL_AUTHORIZED_ROUTES,
  [Role.provider]: PROVIDER_AUTHORIZED_ROUTES,
  [Role.user]: USER_AUTHORIZED_ROUTES,
}
