import { Providers } from '../modules/Theme/Providers'
import './global.css'

export const metadata = {
  title: 'Welcome to marketplace',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Providers>
        <body className="bg-white dark:bg-gray-800">{children}</body>
      </Providers>
    </html>
  )
}
